### ISSUE TITLE
Modify AppCrawler to this scenario

### ISSUE THREAD

**Issue by sibelius** [Eaway/AppCrawler#1]
http://stackoverflow.com/questions/37923618/is-there-any-android-automation-robot

I want to create a script that will:
- Open Google Play Store app
- Download my application
- Mark it as always update
- Mark all the others applications to not update at all

Do u think I can modify AppCrawler to achieve this?

**Comment by Eaway** [comment]
Hi,

I think what you need is the android UIAutomator.
https://developer.android.com/training/testing/ui-testing/uiautomator-testing.html

Thanks.

**Comment by sibelius** [comment]
I'll try that tks
